SELECT 'User' AS table_name, count(*) AS null_tenant_rows FROM "User" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ConsentGrant' AS table_name, count(*) AS null_tenant_rows FROM "ConsentGrant" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PushSubscription' AS table_name, count(*) AS null_tenant_rows FROM "PushSubscription" WHERE "tenantId" IS NULL
UNION ALL SELECT 'EmailChangeRequest' AS table_name, count(*) AS null_tenant_rows FROM "EmailChangeRequest" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PasswordResetToken' AS table_name, count(*) AS null_tenant_rows FROM "PasswordResetToken" WHERE "tenantId" IS NULL
UNION ALL SELECT 'DeletionRequest' AS table_name, count(*) AS null_tenant_rows FROM "DeletionRequest" WHERE "tenantId" IS NULL
UNION ALL SELECT 'EntryDeepening' AS table_name, count(*) AS null_tenant_rows FROM "EntryDeepening" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PsycheNode' AS table_name, count(*) AS null_tenant_rows FROM "PsycheNode" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PsycheEdge' AS table_name, count(*) AS null_tenant_rows FROM "PsycheEdge" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PsycheExtraction' AS table_name, count(*) AS null_tenant_rows FROM "PsycheExtraction" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PsycheAudit' AS table_name, count(*) AS null_tenant_rows FROM "PsycheAudit" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PatternArchetype' AS table_name, count(*) AS null_tenant_rows FROM "PatternArchetype" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PatternLink' AS table_name, count(*) AS null_tenant_rows FROM "PatternLink" WHERE "tenantId" IS NULL
UNION ALL SELECT 'LibraryFolder' AS table_name, count(*) AS null_tenant_rows FROM "LibraryFolder" WHERE "tenantId" IS NULL
UNION ALL SELECT 'LibraryItem' AS table_name, count(*) AS null_tenant_rows FROM "LibraryItem" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ClientProfile' AS table_name, count(*) AS null_tenant_rows FROM "ClientProfile" WHERE "tenantId" IS NULL
UNION ALL SELECT 'HumanDesignChart' AS table_name, count(*) AS null_tenant_rows FROM "HumanDesignChart" WHERE "tenantId" IS NULL
UNION ALL SELECT 'BirthChartCore' AS table_name, count(*) AS null_tenant_rows FROM "BirthChartCore" WHERE "tenantId" IS NULL
UNION ALL SELECT 'LensResult' AS table_name, count(*) AS null_tenant_rows FROM "LensResult" WHERE "tenantId" IS NULL
UNION ALL SELECT 'IntegrativeProfile' AS table_name, count(*) AS null_tenant_rows FROM "IntegrativeProfile" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ArtifactVersion' AS table_name, count(*) AS null_tenant_rows FROM "ArtifactVersion" WHERE "tenantId" IS NULL
UNION ALL SELECT 'IntegrativeReading' AS table_name, count(*) AS null_tenant_rows FROM "IntegrativeReading" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ResonanceMark' AS table_name, count(*) AS null_tenant_rows FROM "ResonanceMark" WHERE "tenantId" IS NULL
UNION ALL SELECT 'IntegrationGuide' AS table_name, count(*) AS null_tenant_rows FROM "IntegrationGuide" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ClientGoal' AS table_name, count(*) AS null_tenant_rows FROM "ClientGoal" WHERE "tenantId" IS NULL
UNION ALL SELECT 'BeliefWork' AS table_name, count(*) AS null_tenant_rows FROM "BeliefWork" WHERE "tenantId" IS NULL
UNION ALL SELECT 'InterventionOutcome' AS table_name, count(*) AS null_tenant_rows FROM "InterventionOutcome" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AskRecordAnswer' AS table_name, count(*) AS null_tenant_rows FROM "AskRecordAnswer" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PracticeSetting' AS table_name, count(*) AS null_tenant_rows FROM "PracticeSetting" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Note' AS table_name, count(*) AS null_tenant_rows FROM "Note" WHERE "tenantId" IS NULL
UNION ALL SELECT 'HandwrittenNote' AS table_name, count(*) AS null_tenant_rows FROM "HandwrittenNote" WHERE "tenantId" IS NULL
UNION ALL SELECT 'RecordingConsent' AS table_name, count(*) AS null_tenant_rows FROM "RecordingConsent" WHERE "tenantId" IS NULL
UNION ALL SELECT 'RecordingDraft' AS table_name, count(*) AS null_tenant_rows FROM "RecordingDraft" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SessionTranscript' AS table_name, count(*) AS null_tenant_rows FROM "SessionTranscript" WHERE "tenantId" IS NULL
UNION ALL SELECT 'NoteScan' AS table_name, count(*) AS null_tenant_rows FROM "NoteScan" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Conversation' AS table_name, count(*) AS null_tenant_rows FROM "Conversation" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Message' AS table_name, count(*) AS null_tenant_rows FROM "Message" WHERE "tenantId" IS NULL
UNION ALL SELECT 'StageChange' AS table_name, count(*) AS null_tenant_rows FROM "StageChange" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Package' AS table_name, count(*) AS null_tenant_rows FROM "Package" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SessionCredit' AS table_name, count(*) AS null_tenant_rows FROM "SessionCredit" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PriceBook' AS table_name, count(*) AS null_tenant_rows FROM "PriceBook" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Charge' AS table_name, count(*) AS null_tenant_rows FROM "Charge" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SquareCustomerLink' AS table_name, count(*) AS null_tenant_rows FROM "SquareCustomerLink" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ExternalPayment' AS table_name, count(*) AS null_tenant_rows FROM "ExternalPayment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Worksheet' AS table_name, count(*) AS null_tenant_rows FROM "Worksheet" WHERE "tenantId" IS NULL
UNION ALL SELECT 'WorksheetAssignment' AS table_name, count(*) AS null_tenant_rows FROM "WorksheetAssignment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'WorksheetResponse' AS table_name, count(*) AS null_tenant_rows FROM "WorksheetResponse" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AssistGrant' AS table_name, count(*) AS null_tenant_rows FROM "AssistGrant" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AuditEvent' AS table_name, count(*) AS null_tenant_rows FROM "AuditEvent" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Course' AS table_name, count(*) AS null_tenant_rows FROM "Course" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Chapter' AS table_name, count(*) AS null_tenant_rows FROM "Chapter" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Lesson' AS table_name, count(*) AS null_tenant_rows FROM "Lesson" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Enrollment' AS table_name, count(*) AS null_tenant_rows FROM "Enrollment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'LessonProgress' AS table_name, count(*) AS null_tenant_rows FROM "LessonProgress" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SessionPrep' AS table_name, count(*) AS null_tenant_rows FROM "SessionPrep" WHERE "tenantId" IS NULL
UNION ALL SELECT 'RecordItem' AS table_name, count(*) AS null_tenant_rows FROM "RecordItem" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Prompt' AS table_name, count(*) AS null_tenant_rows FROM "Prompt" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Assignment' AS table_name, count(*) AS null_tenant_rows FROM "Assignment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PromptResponse' AS table_name, count(*) AS null_tenant_rows FROM "PromptResponse" WHERE "tenantId" IS NULL
UNION ALL SELECT 'LogEntry' AS table_name, count(*) AS null_tenant_rows FROM "LogEntry" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Invite' AS table_name, count(*) AS null_tenant_rows FROM "Invite" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SchedulingConfig' AS table_name, count(*) AS null_tenant_rows FROM "SchedulingConfig" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AvailabilityRule' AS table_name, count(*) AS null_tenant_rows FROM "AvailabilityRule" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AvailabilityException' AS table_name, count(*) AS null_tenant_rows FROM "AvailabilityException" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Appointment' AS table_name, count(*) AS null_tenant_rows FROM "Appointment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Lead' AS table_name, count(*) AS null_tenant_rows FROM "Lead" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ConnectedPaymentAccount' AS table_name, count(*) AS null_tenant_rows FROM "ConnectedPaymentAccount" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Payment' AS table_name, count(*) AS null_tenant_rows FROM "Payment" WHERE "tenantId" IS NULL
UNION ALL SELECT 'SessionCapture' AS table_name, count(*) AS null_tenant_rows FROM "SessionCapture" WHERE "tenantId" IS NULL
UNION ALL SELECT 'IntakeFlow' AS table_name, count(*) AS null_tenant_rows FROM "IntakeFlow" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ClientHintState' AS table_name, count(*) AS null_tenant_rows FROM "ClientHintState" WHERE "tenantId" IS NULL
UNION ALL SELECT 'ActivityEvent' AS table_name, count(*) AS null_tenant_rows FROM "ActivityEvent" WHERE "tenantId" IS NULL
UNION ALL SELECT 'TenantBilling' AS table_name, count(*) AS null_tenant_rows FROM "TenantBilling" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Reading' AS table_name, count(*) AS null_tenant_rows FROM "Reading" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AgreementTemplate' AS table_name, count(*) AS null_tenant_rows FROM "AgreementTemplate" WHERE "tenantId" IS NULL
UNION ALL SELECT 'Agreement' AS table_name, count(*) AS null_tenant_rows FROM "Agreement" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AgreementEvent' AS table_name, count(*) AS null_tenant_rows FROM "AgreementEvent" WHERE "tenantId" IS NULL
UNION ALL SELECT 'PatternElection' AS table_name, count(*) AS null_tenant_rows FROM "PatternElection" WHERE "tenantId" IS NULL
UNION ALL SELECT 'AgreementFile' AS table_name, count(*) AS null_tenant_rows FROM "AgreementFile" WHERE "tenantId" IS NULL
ORDER BY null_tenant_rows DESC, table_name;
