-- PLATFORM — null-tenant convergence. Null tenantId has always meant
-- "owned by the default tenant"; this makes it literal so that ZERO null
-- rows becomes an auditable invariant: the scoped client stamps every
-- request-path create, seeds stamp on completion, and the nightly audit
-- fails on any drift. Covers rows created between the migration-34
-- backfill and the scoped client's deploy. Idempotent by shape.

UPDATE "Appointment" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ArtifactVersion" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "AskRecordAnswer" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Assignment" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "AssistGrant" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "AuditEvent" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "AvailabilityException" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "AvailabilityRule" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "BeliefWork" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "BirthChartCore" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Chapter" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Charge" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ClientGoal" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ClientProfile" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ConsentGrant" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Conversation" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Course" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "DeletionRequest" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "EmailChangeRequest" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Enrollment" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "EntryDeepening" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ExternalPayment" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "HandwrittenNote" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "HumanDesignChart" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "IntegrationGuide" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "IntegrativeProfile" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "IntegrativeReading" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "InterventionOutcome" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Invite" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Lead" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "LensResult" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Lesson" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "LessonProgress" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "LibraryFolder" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "LibraryItem" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "LogEntry" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Message" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Note" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "NoteScan" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Package" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PasswordResetToken" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PatternArchetype" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PatternLink" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PracticeSetting" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PriceBook" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Prompt" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PromptResponse" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PsycheAudit" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PsycheEdge" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PsycheExtraction" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PsycheNode" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "PushSubscription" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "RecordItem" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "RecordingConsent" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "RecordingDraft" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "ResonanceMark" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "SchedulingConfig" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "SessionCredit" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "SessionPrep" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "SessionTranscript" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "SquareCustomerLink" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "StageChange" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "User" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "Worksheet" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "WorksheetAssignment" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
UPDATE "WorksheetResponse" SET "tenantId" = 'tnt_valentina_000000001' WHERE "tenantId" IS NULL;
