-- PLATFORM Phase 0.5 — direct tenant scope on EVERY per-client table
-- (pulled forward from later phases). Additive-only: nullable column +
-- backfill to the default tenant. Same legacy rule as Phase 0.4.

ALTER TABLE "ConsentGrant" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PushSubscription" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "EmailChangeRequest" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PasswordResetToken" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "DeletionRequest" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "EntryDeepening" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PsycheNode" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PsycheEdge" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PsycheExtraction" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PsycheAudit" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LibraryFolder" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LibraryItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "ClientProfile" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "HumanDesignChart" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "BirthChartCore" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LensResult" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "IntegrativeProfile" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "ArtifactVersion" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "IntegrativeReading" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "ResonanceMark" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "IntegrationGuide" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "ClientGoal" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "BeliefWork" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "InterventionOutcome" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "AskRecordAnswer" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Note" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "HandwrittenNote" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "RecordingConsent" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "RecordingDraft" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SessionTranscript" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "NoteScan" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Conversation" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Message" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "StageChange" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Package" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SessionCredit" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Charge" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SquareCustomerLink" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "ExternalPayment" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "WorksheetAssignment" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "WorksheetResponse" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "AssistGrant" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "AuditEvent" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Chapter" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Lesson" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Enrollment" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LessonProgress" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SessionPrep" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "RecordItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Assignment" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PromptResponse" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LogEntry" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "AvailabilityRule" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "AvailabilityException" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "tenantId" TEXT;

UPDATE "ConsentGrant" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PushSubscription" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "EmailChangeRequest" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PasswordResetToken" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "DeletionRequest" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "EntryDeepening" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PsycheNode" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PsycheEdge" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PsycheExtraction" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PsycheAudit" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "LibraryFolder" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "LibraryItem" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "ClientProfile" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "HumanDesignChart" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "BirthChartCore" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "LensResult" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "IntegrativeProfile" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "ArtifactVersion" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "IntegrativeReading" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "ResonanceMark" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "IntegrationGuide" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "ClientGoal" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "BeliefWork" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "InterventionOutcome" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "AskRecordAnswer" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Note" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "HandwrittenNote" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "RecordingConsent" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "RecordingDraft" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "SessionTranscript" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "NoteScan" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Conversation" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Message" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "StageChange" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Package" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "SessionCredit" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Charge" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "SquareCustomerLink" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "ExternalPayment" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "WorksheetAssignment" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "WorksheetResponse" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "AssistGrant" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "AuditEvent" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Chapter" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Lesson" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Enrollment" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "LessonProgress" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "SessionPrep" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "RecordItem" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Assignment" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "PromptResponse" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "LogEntry" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "AvailabilityRule" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "AvailabilityException" SET "tenantId" = 'tnt_valentina_000000001';
UPDATE "Appointment" SET "tenantId" = 'tnt_valentina_000000001';
